---
- name: Verify if /etc/apt/apt.conf.d exists
  ansible.builtin.stat:
    path: /etc/apt/apt.conf.d
  register: apt_conf_d

- name: Set the use_apt_conf_d
  ansible.builtin.set_fact:
    use_apt_conf_d: true
  when:
    - apt_conf_d.stat.exists
    - apt_conf_d.stat.isdir

- name: Set the use_apt_conf_d to false
  ansible.builtin.set_fact:
    use_apt_conf_d: false
  when:
    use_apt_conf_d is undefined

- name: Configure /etc/apt/apt.conf.d
  ansible.builtin.import_tasks: apt/etc_apt_conf_d_proxy.yml
  when:
    use_apt_conf_d

- name: Configure /etc/apt/apt.conf
  ansible.builtin.import_tasks: apt/etc_apt_conf.yml
  when:
    not use_apt_conf_d
