- name: enable proxy in /etc/dnf/dnf.conf
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: proxy
    value: '{{ proxy.pkg_mgr_proxy }}'
  when:
    proxy.pkg_mgr_proxy != 'absent'

- name: disable proxy in /etc/dnf/dnf.conf
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: proxy
    state: absent
  when:
    proxy.pkg_mgr_proxy == 'absent'
