- name: enable proxy in /etc/pacman.conf
  ini_file:
    path: /etc/pacman.conf
    section: options
    option: XferCommand
    value: '/usr/bin/curl -L -C - -f -o %o %u -x {{ proxy.pkg_mgr_proxy }}'
  when:
    proxy.pkg_mgr_proxy != 'absent'

- name: disable proxy in /etc/pacman.conf
  ini_file:
    path: /etc/pacman.conf
    section: options
    option: XferCommand
    state: absent
  when:
    proxy.pkg_mgr_proxy == 'absent'
