---
- name: Verify if /usr/local/etc/pkg.conf exists
  stat:
    path: /usr/local/etc/pkg.conf
  register:
    etc_local_pkg_conf

- name: Ensure that /usr/local/etc/pkg.conf exists
  file:
    path: /usr/local/etc/pkg.conf
    state: touch
    mode: "0644"
    owner: root
    group: wheel
  when:
    - proxy.pkg_mgr_proxy != 'absent'
    - not etc_local_pkg_conf.stat.exists

- name: Add proxy to /usr/local/etc/pkg.conf
  blockinfile:
    path: /usr/local/etc/pkg.conf
    block: |
      pkg_env: {
        http_proxy: "{{ proxy.pkg_mgr_proxy }}"
      }
  when:
    proxy.pkg_mgr_proxy != 'absent'

- name: Remove proxy from /usr/local/etc/pkg.conf
  block:
    - name: Remove http_proxy
      lineinfile:
        path: /usr/local/etc/pkg.conf
        regexp: ".*http_proxy:"
        state: absent
    - name: Removed ansible managed header
      replace:
        path: /usr/local/etc/pkg.conf
        regexp: '# BEGIN ANSIBLE MANAGED BLOCK\n*.*pkg_env: {\n*\s*}\s*\n*# END ANSIBLE MANAGED BLOCK'
        replace: ''
    - name: Remove pkg_env
      replace:
        path: /usr/local/etc/pkg.conf
        regexp: '.*pkg_env: {\n*\s*}\s*'
        replace: ''
  when:
    - proxy.pkg_mgr_proxy == 'absent'
    - etc_local_pkg_conf.stat.exists
