---
- name: Add proxy to /etc/profile
  ansible.builtin.lineinfile:
    path: /etc/profile
    regexp: "^.*{{ item }}_proxy.*=.*{{ proxy.etc_profile_proxy }}"
    line: "{{ item }}_proxy={{ proxy.etc_profile_proxy }}"
- name: Add proxy export to /etc/profile
  ansible.builtin.lineinfile:
    path: /etc/profile
    regexp: "^.*export {{ item }}_proxy"
    line: "export {{ item }}_proxy"
