---
- name: Setup proxy in /etc/csh.cshrc
  ansible.builtin.include_tasks: etc_csh_cshrc/set_etc_csh_cshrc_proxy.yml
  when:
    proxy.etc_csh_cshrc_proxy != "absent"
- name: Remove proxy setup from /etc/csh.cshrc
  ansible.builtin.include_tasks: etc_csh_cshrc/unset_etc_csh_cshrc_proxy.yml
  when:
    proxy.etc_csh_cshrc_proxy == "absent"
