- name: setup proxy in /etc/profile
  include_tasks: etc_profile/set_etc_profile_proxy.yml
  when:
    proxy.etc_profile_proxy != 'absent'
- name: remove proxy setup from /etc/profile
  include_tasks: etc_profile/unset_etc_profile_proxy.yml
  when:
    proxy.etc_profile_proxy == 'absent'
