---
- name: Unset noproxy in /etc/profile
  ansible.builtin.lineinfile:
    path: /etc/profile
    regexp: "^.*no_proxy.*=.*"
    state: absent
- name: Remove export no_proxy to /etc/profile
  ansible.builtin.lineinfile:
    path: /etc/profile
    regexp: "'^.*export no_proxy"
    state: absent
